pipeline:
  name: gkalipalli-ci-cd-pipeline-v1
  identifier: gkalipallicicdpipelinev1
  projectIdentifier: SFTY_Training
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: gowtham_nanda
        repoName: Demo-CI-CD
        build: <+input>
        sparseCheckout: []
  stages:
    - stage:
        name: CI
        identifier: CI
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec:
              size: flex
              imageSpec:
                imageName: ubuntu-24
          execution:
            steps:
              - step:
                  type: BuildAndPushGAR
                  name: BuildAndPushGAR_1
                  identifier: BuildAndPushGAR_1
                  spec:
                    connectorRef: gkalipalliGCPConnector
                    host: us-central1-docker.pkg.dev
                    projectID: bustling-tuner-482104-a0
                    imageName: harness-repo/springboot-app
                    tags:
                      - <+pipeline.sequenceId>
              - step:
                  type: Run
                  name: Update k8s Manifest files
                  identifier: Update_k8s_Manifest_files
                  spec:
                    shell: Sh
                    command: "sed -i \"s|image: .*|image: us-central1-docker.pkg.dev/bustling-tuner-482104-a0/harness-repo/springboot-app:<+pipeline.sequenceId>|g\" k8s/deployment.yaml"
                  description: This will updates K8s manifest files with new image tag..
    - stage:
        name: CD
        identifier: CD
        tags: {}
        template:
          templateRef: gkalpalliCICDpipeline_Demo
          versionLabel: v1
