pipeline:
  name: gkalipalli-ci-cd-pipeline-v1
  identifier: gkalipallicicdpipelinev1
  projectIdentifier: SFTY_Training
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: gowtham_nanda
        repoName: Demo-CI-CD
        build: <+input>
        sparseCheckout: []
  stages:
    - stage:
        name: CI
        identifier: CI
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec:
              size: flex
              imageSpec:
                imageName: ubuntu-24
          execution:
            steps:
              - step:
                  type: BuildAndPushGAR
                  name: BuildAndPushGAR_1
                  identifier: BuildAndPushGAR_1
                  spec:
                    connectorRef: gkalipalliGCPConnector
                    host: us-central1-docker.pkg.dev
                    projectID: bustling-tuner-482104-a0
                    imageName: springboot-app
                    tags:
                      - <+pipeline.sequenceId>
    - stage:
        name: CD
        identifier: CD
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: gksvc
          environment:
            environmentRef: gkenv
            deployToAll: false
            infrastructureDefinitions:
              - identifier: kubernetes
          execution:
            steps:
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
