pipeline:
  name: gk-ci-cd-pipelines-475
  identifier: gkcicdpipelines475
  projectIdentifier: SFTY_Training
  orgIdentifier: default
  tags:
    ai_generated: "true"
  properties:
    ci:
      codebase:
        connectorRef: gkalipallinewgitconnector
        repoName: Demo-CI-CD
        build: <+input>
        sparseCheckout: []
  stages:
    - stage:
        name: CI Stages
        identifier: CI_Stages
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec:
              size: flex
              imageSpec:
                imageName: ubuntu-24
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: mvn package -DskipTests -Dsonar.java.binaries=target/classes
              - step:
                  type: Sonarqube
                  name: Sonarqube_1
                  identifier: Sonarqube_1
                  spec:
                    mode: orchestration
                    config: default
                    target:
                      type: repository
                      detection: auto
                    advanced:
                      log:
                        level: info
                    auth:
                      access_token: sqa_c237ba759060346a648b0a78268396ce1f0e1cd7
                      domain: http://34.27.136.50:9000
                      ssl: true
                    tool:
                      java:
                        libraries: target/*.jar
                        binaries: target/classes
                      project_key: harness-build
              - step:
                  type: GCSUpload
                  name: GCSUpload_1
                  identifier: GCSUpload_1
                  spec:
                    connectorRef: gk475gcplatestconnector
                    bucket: demo-gcp-artifact-bucket/Springboot.jar
                    sourcePath: /harness/target/springboot-gke-demo-1.0.0.jar
              - step:
                  type: BuildAndPushGAR
                  name: BuildAndPushGAR_1
                  identifier: BuildAndPushGAR_1
                  spec:
                    connectorRef: gk475gcplatestconnector
                    host: us.gcr.io
                    projectID: gkalipalli
                    imageName: spring-boot-app
                    tags:
                      - v1
    - stage:
        name: CD Stage
        identifier: CD_Stage
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: gksvc475v1
            serviceInputs:
              serviceDefinition:
                type: Kubernetes
                spec:
                  variables:
                    - name: IMAGE_TAG
                      type: String
                      value: <+input>
                  artifacts:
                    primary:
                      primaryArtifactRef: primary
            gitBranch: main
          environment:
            environmentRef: gkenv475v1
            gitBranch: main
            deployToAll: false
            infrastructureDefinitions:
              - identifier: gkinfra475v1
          execution:
            steps:
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
              - step:
                  type: K8sCanaryDeploy
                  name: K8sCanaryDeploy_1
                  identifier: K8sCanaryDeploy_1
                  spec:
                    skipDryRun: false
                    instanceSelection:
                      type: Count
                      spec:
                        count: 1
                  timeout: 10m
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
  description: This pipeline was updated by Harness AI on 2025-12-31 05:56:29 UTC by Gowtham.
